// CONTROL DE ACCESO
export * from '../../Software/software/software.component';
export * from './colegios/colegios.component';
export * from './softwares/softwares.component';
export * from './sedes/sedes.component';
export * from './usuario/usuario.component';
export * from './company-software/company-software.component';
export * from './rol/rol.component';
export * from './menus/menus.component';
export * from './menu-rol/menu-rol.component';
export * from './menu-usuario/menu-usuario.component';